library(SRAdb)
library(pcaMethods)
library(Seurat)
library(dplyr)
library(reticulate)

parent_dir = "DIRECTORY LOCATION WHERE FILES ARE STORED"
sc_ET1 <- ReadH5AD(file = paste(parent_dir,"sc_data_ET1_final.h5ad", sep=""))
sc_ET2 <- ReadH5AD(file = paste(parent_dir,"sc_data_ET2_final.h5ad", sep=""))
sc_ET3 <- ReadH5AD(file = paste(parent_dir,"sc_data_ET3_final.h5ad", sep=""))
sc_healthy <- ReadH5AD(file = paste(parent_dir,"sc_data_healthy_final.h5ad", sep=""))
sc_ET_V617L <- ReadH5AD(file = paste(parent_dir,"sc_data_ET_V617L_final.h5ad", sep=""))
sc_PV1 <- ReadH5AD(file = paste(parent_dir,"sc_data_PV1_final.h5ad", sep=""))
sc_PV2 <- ReadH5AD(file = paste(parent_dir,"sc_data_PV2_final.h5ad", sep=""))
sc_PV3 <- ReadH5AD(file = paste(parent_dir,"sc_data_PV3_final.h5ad", sep=""))
sc_healthy2 <- ReadH5AD(file = paste(parent_dir,"sc_data_healthy2_final.h5ad", sep=""))
sc_healthy3 <- ReadH5AD(file = paste(parent_dir,"sc_data_healthy3_final.h5ad", sep=""))

sc_ET1 <- FindVariableFeatures(object = sc_ET1, verbose = FALSE)
sc_ET2 <- FindVariableFeatures(object = sc_ET2, verbose = FALSE)
sc_ET3 <- FindVariableFeatures(object = sc_ET3, verbose = FALSE)
sc_ET_V617L <- FindVariableFeatures(object = sc_ET_V617L, verbose = FALSE)
sc_healthy <- FindVariableFeatures(object = sc_healthy, verbose = FALSE)
sc_healthy2 <- FindVariableFeatures(object = sc_healthy2, verbose = FALSE)
sc_healthy3 <- FindVariableFeatures(object = sc_healthy3, verbose = FALSE)
sc_PV1 <- FindVariableFeatures(object = sc_PV1, verbose = FALSE)
sc_PV2 <- FindVariableFeatures(object = sc_PV2, verbose = FALSE)
sc_PV3 <- FindVariableFeatures(object = sc_PV3, verbose = FALSE)

merged_all.list = c(sc_healthy, sc_healthy2, sc_healthy3, sc_ET1, sc_ET3, sc_ET2, sc_PV1, sc_ET_V617L, sc_PV2, sc_PV3)
merged_all.anchors <- FindIntegrationAnchors(object.list = merged_all.list, dims = 1:30)
scanpy.integrated <- IntegrateData(anchorset = merged_all.anchors, dims = 1:30)
merged.loom <- as.loom(scanpy.integrated, filename = paste(parent_dir,"sc_data_integrated_all_final.loom", sep=""), verbose = FALSE)
merged.loom$close_all()